name: Cloud check in action
on:
  push:
    branches:
      - main
  watch:
    types: started
  schedule:
    - cron: 35 3 * * *
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: user
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: init
      run: npm install
    - name: run
      env:
        TY_USER_NAME: ${{secrets.TY_USER_NAME}}
        TY_PASSWORD: ${{secrets.TY_PASSWORD}}
        TY_USER_NAME1: ${{secrets.TY_USER_NAME1}}
        TY_PASSWORD1: ${{secrets.TY_PASSWORD1}}
        TY_USER_NAME2: ${{secrets.TY_USER_NAME2}}
        TY_PASSWORD2: ${{secrets.TY_PASSWORD2}}
        TY_USER_NAM3: ${{secrets.TY_USER_NAM3}}
        TY_PASSWORD3: ${{secrets.TY_PASSWORD3}}
        TY_USER_NAME4: ${{secrets.TY_USER_NAME4}}
        TY_PASSWORD4: ${{secrets.TY_PASSWORD4}}
      run: npm start
